name: CI  # 工作流名称

on:
  push:
    branches:
      - main # 触发工作流的分支，此处为主分支

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        env: 
          MY_REGISTRY_HOST: ${{ secrets.MY_REGISTRY_HOST }}
          MY_APP_PATH: ${{ secrets.MY_APP_PATH }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          envs: MY_REGISTRY_HOST, MY_APP_PATH
          script: |
            cd $MY_APP_PATH
            make pull
            make build
            make install
