name: CI  # 工作流名称

on:
  push:
    branches:
      - main # 触发工作流的分支，此处为主分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # 步骤名称
        uses: actions/checkout@v3 # 使用GitHub官方的checkout操作获取代码

      - name: Build Docker image
        run: |
          docker build -t ywtest/my-app:${{ github.sha }} -f docker/Dockerfile .
          docker tag ywtest/my-app:${{ github.sha }} ywtest/my-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ywtest/my-app:latest
          docker push ywtest/my-app:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          envs: |
            MY_REGISTRY_HOST=${{ secrets.MY_REGISTRY_HOST }}
            MY_APP_PATH=${{ secrets.MY_APP_PATH }}
          script: |
            docker pull $MY_REGISTRY_HOST/ywtest/my-app:latest
            cd $MY_APP_PATH
            git pull origin main
            sed -i 's|^\( *image: \).*|\1$MY_REGISTRY_HOST|' docker-compose.yml
            docker compose up -d server 

